// <auto-generated />
namespace BettingPredictorV3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fixfixturesforeignkeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixfixturesforeignkeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201912181741594_fix-fixtures-foreignkeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
